import type { DnsRecord } from "./dnsTypes";

/**
 * A single nsupdate operation derived from comparing two record sets.
 */
export interface NsupdateOp {
    kind: "add" | "delete" | "delete-rrset";
    zone: string;
    name: string;
    type: string;
    ttl?: number;
    rdata?: string;
}

/**
 * Compute the minimal set of nsupdate operations needed to transform
 * `current` records into `next` records.
 *
 * Uses (name, type, data) as the composite identity key since client-side
 * record IDs are ephemeral (generated by the frontend, not persisted).
 *
 * @param zone  The DNS zone name these records belong to (e.g. "example.com")
 * @param current  The records currently in the zone (from the zone file)
 * @param next  The desired records (from the edit page user)
 * @returns  An ordered array of nsupdate operations
 */
export function diffRecords(
    zone: string,
    current: DnsRecord[],
    next: DnsRecord[],
): NsupdateOp[] {
    const ops: NsupdateOp[] = [];

    // Build identity maps using (name, type, data) as composite key
    const currentMap = new Map<string, DnsRecord>();
    for (const r of current) {
        currentMap.set(recordKey(r), r);
    }

    const nextMap = new Map<string, DnsRecord>();
    for (const r of next) {
        nextMap.set(recordKey(r), r);
    }

    // ── Records to delete ────────────────────────────────────────
    for (const r of current) {
        if (nextMap.has(recordKey(r))) {
            continue; // unchanged — skip
        }

        // Check if the same (name, type) pair still exists in "next"
        // but with different data. If so, we need a precise delete
        // (delete the old exact record) rather than a full RRset delete.
        const sameNameTypeExists = next.some(
            (n) => n.name === r.name && n.type === r.type,
        );

        if (sameNameTypeExists) {
            // The RRset still has records but this specific one is gone.
            // Use a precise delete of the exact rdata.
            ops.push({
                kind: "delete",
                zone,
                name: r.name,
                type: r.type,
                rdata: r.data,
            });
        } else {
            // The entire RRset for (name, type) is gone.
            ops.push({
                kind: "delete-rrset",
                zone,
                name: r.name,
                type: r.type,
            });
        }
    }

    // ── Records to add ──────────────────────────────────────────
    for (const r of next) {
        if (currentMap.has(recordKey(r))) {
            continue; // already exists — skip
        }

        ops.push({
            kind: "add",
            zone,
            name: r.name,
            type: r.type,
            ttl: r.ttl,
            rdata: r.data,
        });
    }

    return ops;
}

/**
 * Normalise a DNS owner name so nsupdate interprets it correctly.
 *
 * nsupdate's `zone` command does NOT change the origin — the default
 * origin is always `.` (root). A bare label like `www` is therefore
 * treated as `www.`, which is NOT inside the zone and triggers the
 * `NOTZONE` error. To get a name into the zone we have to make it an
 * absolute FQDN with a trailing dot, which means appending the zone
 * for simple labels.
 *
 * - `@`                       → `@`               (nsupdate special, zone apex)
 * - `name.` (trailing dot)    → as-is              (already absolute)
 * - `sub.name` (has dot)      → `sub.name.`        (just dot-terminate)
 * - `www` (no dot)            → `www.{zone}.`      (build FQDN)
 *
 * Wildcard `*` is left as-is — nsupdate treats it as a literal name
 * and BIND recognises it as the wildcard owner when present in the
 * zone (it is, e.g. `*.foo.example.com`).
 */
function normaliseNameForNsupdate(name: string, zone: string): string {
    if (name === "@") return name;
    if (name === "*") return name;
    if (name.endsWith(".")) return name;
    if (name.includes(".")) return name + ".";
    return `${name}.${zone}.`;
}

/**
 * Convert an array of NsupdateOp into the command lines expected
 * by an nsupdate transaction script (zone + update add/delete).
 */
export function opsToCommands(ops: NsupdateOp[]): string[] {
    const commands: string[] = [];
    let currentZone = "";

    for (const op of ops) {
        if (op.zone !== currentZone) {
            commands.push(`zone ${op.zone}`);
            currentZone = op.zone;
        }

        const name = normaliseNameForNsupdate(op.name, op.zone);

        switch (op.kind) {
            case "add":
                commands.push(
                    `update add ${name} ${op.ttl ?? 3600} IN ${op.type} ${op.rdata ?? ""}`,
                );
                break;
            case "delete":
                commands.push(
                    `update delete ${name} IN ${op.type} ${op.rdata ?? ""}`,
                );
                break;
            case "delete-rrset":
                commands.push(`update delete ${name} IN ${op.type}`);
                break;
        }
    }

    return commands;
}

function recordKey(r: DnsRecord): string {
    return `${r.name}|${r.type}|${r.data}`;
}
